# https://cirrus-ci.org/examples/
# https://github.com/curl/curl/blob/master/.cirrus.yml

env:
  CIRRUS_CLONE_DEPTH: 5

task:
  matrix:
    - name: Standard, GCC, FreeBSD 12.1
      freebsd_instance:
        image_family: freebsd-12-1
      env:
      pkginstall_script:
        - pkg update -f
        - pkg install -y bash gmake gcc autoconf automake autopoint libtool pkg-config
      configure_script:
      compile_script:
      test_script:
        - cp ci_tests/test_modules.sh .
        - bash test_modules.sh
        - echo "-----"; cat result.txt

    - name: Standard, Clang, FreeBSD 12.1
      freebsd_instance:
        image_family: freebsd-12-1
      env:
        - CC=clang
        - CXX=clang++
      pkginstall_script:
        - pkg update -f
        - pkg install -y bash gmake llvm80 autoconf automake autopoint libtool pkg-config
      configure_script:
      compile_script:
      test_script:
        - cp ci_tests/test_modules.sh .
        - bash test_modules.sh
        - echo "-----"; cat result.txt

    - name: Standard, GCC, FreeBSD 13.0 (snap)
      freebsd_instance:
        image_family: freebsd-13-0-snap
      env:
      pkginstall_script:
        - pkg update -f
        - pkg install -y bash gmake gcc autoconf automake autopoint libtool pkg-config
      configure_script:
      compile_script:
      test_script:
        - cp ci_tests/test_modules.sh .
        - bash test_modules.sh
        - echo "-----"; cat result.txt
    - name: Standard, Clang, FreeBSD 13.0 (snap)
      freebsd_instance:
        image_family: freebsd-13-0-snap
      env:
        - CC=clang
        - CXX=clang++
      pkginstall_script:
        - pkg update -f
        - pkg install -y bash gmake llvm90 autoconf automake autopoint libtool pkg-config
      configure_script:
      compile_script:
      test_script:
        - cp ci_tests/test_modules.sh .
        - bash test_modules.sh
        - echo "-----"; cat result.txt