# https://cirrus-ci.org/examples/
# https://github.com/curl/curl/blob/master/.cirrus.yml

env:
  CIRRUS_CLONE_DEPTH: 5

task:
  matrix:
    - name: Standard, GCC, FreeBSD 12.1
      freebsd_instance:
        image_family: freebsd-12-1
      pkginstall_script:
        - pkg update -f
        - pkg install -y bash gmake gcc autoconf automake libtool
      configure_script:
      compile_script:
      test_script:
        - cp ci_tests/test_modules.sh .
        - bash test_modules.sh
        - echo "-----"; cat result.txt
    - name: Standard, Clang, FreeBSD 12.1
      freebsd_instance:
        image_family: freebsd-12-1
      pkginstall_script:
        - pkg update -f
        - pkg install -y bash gmake llvm80 autoconf automake libtool
      configure_script:
      compile_script:
      test_script:
        - export CC=/usr/local/bin/clang80
        - export CXX=/usr/local/bin/clang++80
        - cp ci_tests/test_modules.sh .
        - bash test_modules.sh
        - echo "-----"; cat result.txt
    - name: Standard, GCC, FreeBSD 13.0 (snap)
      freebsd_instance:
        image_family: freebsd-13-0-snap
      pkginstall_script:
        - pkg update -f
        - pkg install -y bash gmake gcc autoconf automake libtool
      configure_script:
      compile_script:
      test_script:
        - cp ci_tests/test_modules.sh .
        - bash test_modules.sh
        - echo "-----"; cat result.txt
    - name: Standard, Clang, FreeBSD 13.0 (snap)
      freebsd_instance:
        image_family: freebsd-13-0-snap
      pkginstall_script:
        - pkg update -f
        - pkg install -y bash gmake llvm90 autoconf automake libtool
      configure_script:
      compile_script:
      test_script:
        - export CC=/usr/local/bin/clang90
        - export CXX=/usr/local/bin/clang++90
        - cp ci_tests/test_modules.sh .
        - bash test_modules.sh
        - echo "-----"; cat result.txt
